"""empty message

Revision ID: c06709f28fd9
Revises: 69b5bac99a35
Create Date: 2019-08-30 14:40:24.081039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06709f28fd9'
down_revision = '69b5bac99a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
